<h1>Balbir Singh</h1>

In [1]:
from __future__ import print_function
import keras
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D
from keras import backend as K

batch_size = 128
num_classes = 10
epochs = 12

# input image dimensions
img_rows, img_cols = 28, 28

# the data, split between train and test sets
(x_train, y_train), (x_test, y_test) = mnist.load_data()

if K.image_data_format() == 'channels_first':
    x_train = x_train.reshape(x_train.shape[0], 1, img_rows, img_cols)
    x_test = x_test.reshape(x_test.shape[0], 1, img_rows, img_cols)
    input_shape = (1, img_rows, img_cols)
else:
    x_train = x_train.reshape(x_train.shape[0], img_rows, img_cols, 1)
    x_test = x_test.reshape(x_test.shape[0], img_rows, img_cols, 1)
    input_shape = (img_rows, img_cols, 1)

x_train = x_train.astype('float32')
x_test = x_test.astype('float32')
x_train /= 255
x_test /= 255
print('x_train shape:', x_train.shape)
print(x_train.shape[0], 'train samples')
print(x_test.shape[0], 'test samples')

# convert class vectors to binary class matrices
y_train = keras.utils.to_categorical(y_train, num_classes)
y_test = keras.utils.to_categorical(y_test, num_classes)

model = Sequential()
model.add(Conv2D(32, kernel_size=(3, 3),
                 activation='relu',
                 input_shape=input_shape))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(num_classes, activation='softmax'))

model.compile(loss=keras.losses.categorical_crossentropy,
              optimizer=keras.optimizers.Adadelta(),
              metrics=['accuracy'])

model.fit(x_train, y_train,
          batch_size=batch_size,
          epochs=epochs,
          verbose=1,
          validation_data=(x_test, y_test))
score = model.evaluate(x_test, y_test, verbose=0)
print('Test loss:', score[0])
print('Test accuracy:', score[1])

Using TensorFlow backend.


11493376/11490434 [==============================] - 2s 0us/step
x_train shape: (60000, 28, 28, 1)
60000 train samples
10000 test samples





Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.


Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where



Train on 60000 samples, validate on 10000 samples
Epoch 1/12





60000/60000 [==============================] - 13s 210us/step - loss: 0.2652 - acc: 0.9190 - val_loss: 0.0582 - val_acc: 0.9805
Epoch 2/12
60000/60000 [==============================] - 5s 83us/step - loss: 0.0869 - acc: 0.9742 - val_loss: 0.0401 - val_acc: 0.9865
Epoch 3/12
60000/60000 [==============================] - 5s 82us/step - loss: 0.0664 - acc: 0.9799 - val_loss: 0.0345 - val_acc: 0.9886
Epoch 4/12
60000/60000 [==============================] - 5s 81us/step - loss: 0.0537 - acc: 0.9839 - val_loss: 0.0281 - val_acc: 0.9907
Epoch 5/12
60000/60000 [==============

In [ ]:
import numpy as np
y_test = np.argmax(y_test,axis=1)
y_pred = model.predict_classes(x_test)

In [13]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))

[[ 977    0    0    0    0    0    1    1    1    0]
 [   0 1130    1    2    0    1    1    0    0    0]
 [   1    1 1024    1    1    0    0    3    1    0]
 [   0    0    2 1006    0    1    0    0    1    0]
 [   0    0    0    0  976    0    2    0    0    4]
 [   1    0    0    7    0  882    2    0    0    0]
 [   4    2    0    1    1    1  949    0    0    0]
 [   0    1    4    2    0    0    0 1020    1    0]
 [   1    0    2    1    0    0    1    1  966    2]
 [   1    1    0    2    4    2    0    2    2  995]]


Comment: CNN gives more than 99% accuracy for mnist.